# Generated by Django 4.0.4 on 2022-05-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acme_Support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CLOSED', 'Closed')], default='pending', max_length=155),
        ),
    ]
